<?php

class OrderBuilderTest extends Illuminate\Foundation\Testing\TestCase
{
    /**
     * The base Builder class (OrderBuilder).
     *
     * @var string
     */
    protected $builderClass = '\App\Models\Builder\OrderBuilder';

    protected $builder;

    protected $subject = '\App\Models\Order';

    protected $orderItemmetaCache = [];

    public function createApplication()
    {
        $app = require __DIR__.'/../../../bootstrap/app.php';

        $app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

        return $app;
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->builder = new $this->builderClass();

        //this data will only fill 2 properties of the OrderItemmetaCache object (_qty and _line_total)
        $this->orderItemmetaCache = [
            \App\Models\OrderItemmetaCache::create([
                'meta_id' => 1,
                'order_item_id' => 1,
                'meta_key' => '_qty',
                'meta_value' => '3'
            ]),
            \App\Models\OrderItemmetaCache::create([
                'meta_id' => 2,
                'order_item_id' => 1,
                'meta_key' => '_line_total',
                'meta_value' => '20.97'
            ]),
        ];
    }

    public function testItemmetaBuilder()
    {
        foreach ($this->orderItemmetaCache as $meta) {
            $this->builder->addOrderItemmetaCache($meta);
        }

        $result = $this->builder->buildItemMeta();

        print_r($result);
    }
}
